name: Deploy

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      target:
        required: true
        default: production
        type: choice
        options: [preview, production]
      mirror:
        required: true
        default: false
        type: boolean

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  ci:
    uses: ./.github/workflows/_ci.yml
    with:
      ghpages: ${{ inputs.mirror == true }}
    secrets: inherit

  deploy-vercel:
    name: Deploy ${{ github.event_name == 'workflow_dispatch' && inputs.target || (github.ref == 'refs/heads/main' && 'production' || 'preview') }}
    needs: ci
    uses: ./.github/workflows/_vercel.yml
    with:
      target: ${{ github.event_name == 'workflow_dispatch' && inputs.target || (github.ref == 'refs/heads/main' && 'production' || 'preview') }}
    secrets: inherit

  deploy-render:
    name: Commit mirror
    needs: ci
    if: ${{ github.event_name == 'push' }}
    uses: ./.github/workflows/_render.yml
    secrets: inherit

  deploy-ghpages:
    name: Static mirror
    needs: ci
    if: ${{ github.ref == 'refs/heads/main' && inputs.mirror == true }}
    uses: ./.github/workflows/_ghpages.yml
    with:
      enabled: true
    secrets: inherit
